# generated by datamodel-codegen:
#   filename:  messages.schema.json

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import ConfigDict, Field, RootModel

from liveclass_protocol._base import StrictBase


class Edit(StrictBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    offset: Annotated[
        int, Field(description='UTF-16 code-unit offset into the base document', ge=0)
    ]
    length: Annotated[
        int, Field(description='UTF-16 code units to delete at offset', ge=0)
    ]
    text: Annotated[str, Field(description='replacement text inserted at offset')]


class ClientInfo(StrictBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    ideType: Literal['vscode', 'headless', 'web', 'other']
    clientVersion: Annotated[str, Field(min_length=1)]


class Limits(StrictBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxMsgBytes: Annotated[int, Field(ge=1)]
    msgsPerSec: Annotated[int, Field(ge=1)]


class DocumentDescriptor(StrictBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentId: UUID
    relativePath: Annotated[str, Field(min_length=1)]
    version: Annotated[int, Field(ge=0)]


class SnapshotData(StrictBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentId: UUID
    version: Annotated[int, Field(ge=0)]
    content: str


class PresenceMember(StrictBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    userId: UUID
    role: Literal['instructor', 'student']
    state: Literal['joined', 'left']
    since: Annotated[int, Field(ge=0)]


class ResumeEntry(StrictBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    documentId: UUID
    lastVersion: Annotated[int, Field(ge=0)]


class Envelope(StrictBase):
    """
    Fields common to every message. sessionId/role are never trusted for authorization — the server resolves them.
    """

    protocol: Literal['1.0']
    type: str
    msgId: UUID
    ts: Annotated[int, Field(ge=0)]
    sessionId: UUID | None = None
    documentId: UUID | None = None


class Connect(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['connect']
    token: Annotated[str, Field(min_length=1)]
    clientInfo: ClientInfo


class ConnectAck(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['connect_ack']
    userId: UUID
    role: Literal['instructor', 'student']
    serverTime: Annotated[int, Field(ge=0)]
    heartbeatIntervalMs: Annotated[int, Field(ge=1)]
    limits: Limits


class Join(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['join']
    sessionId: UUID
    resume: list[ResumeEntry] | None = None


class Welcome(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['welcome']
    sessionId: UUID
    role: Literal['instructor', 'student']
    mode: Literal['observe']
    documents: list[DocumentDescriptor]
    presence: list[PresenceMember]
    snapshots: list[SnapshotData] | None = None


class DocChange(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['doc_change']
    documentId: UUID
    baseVersion: Annotated[int, Field(ge=0)]
    clientOpId: Annotated[str, Field(max_length=128, min_length=1)]
    edits: Annotated[list[Edit], Field(max_length=1000, min_length=1)]


class Ack(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['ack']
    documentId: UUID
    clientOpId: Annotated[str, Field(max_length=128, min_length=1)]
    version: Annotated[int, Field(ge=0)]
    status: Literal['applied']


class DocUpdate(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['doc_update']
    documentId: UUID
    version: Annotated[int, Field(ge=0)]
    baseVersion: Annotated[int, Field(ge=0)]
    edits: Annotated[list[Edit], Field(max_length=1000, min_length=1)]
    originOpId: Annotated[str, Field(max_length=128, min_length=1)]
    authorUserId: UUID


class ResyncRequest(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['resync_request']
    documentId: UUID
    fromVersion: Annotated[int, Field(ge=0)]


class Snapshot(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['snapshot']
    documentId: UUID
    version: Annotated[int, Field(ge=0)]
    content: str


class PresenceUpdate(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['presence_update']
    sessionId: UUID
    members: list[PresenceMember]


class Ping(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['ping']
    nonce: Annotated[str, Field(min_length=1)]


class Pong(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['pong']
    nonce: Annotated[str, Field(min_length=1)]


class SessionClosed(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session_closed']
    reason: Literal['ended', 'paused', 'teacher_disconnected']
    final: bool


class Error(Envelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error']
    code: Literal[
        'PROTOCOL_MISMATCH',
        'UNAUTHORIZED',
        'FORBIDDEN',
        'INVALID_MESSAGE',
        'UNKNOWN_SESSION',
        'UNKNOWN_DOCUMENT',
        'STALE_VERSION',
        'INVALID_VERSION',
        'DUPLICATE_OP',
        'RATE_LIMITED',
        'INTERNAL',
    ]
    message: str
    relatedMsgId: UUID | None = None
    currentVersion: Annotated[int | None, Field(ge=0)] = None


class Checkpoint(Envelope):
    """
    Teacher-uploaded full-document checkpoint (the opaque server never derives content itself).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['checkpoint']
    documentId: UUID
    version: Annotated[int, Field(ge=0)]
    content: str


class Message(
    RootModel[
        Connect
        | ConnectAck
        | Join
        | Welcome
        | DocChange
        | Ack
        | DocUpdate
        | ResyncRequest
        | Snapshot
        | PresenceUpdate
        | Ping
        | Pong
        | SessionClosed
        | Error
        | Checkpoint
    ]
):
    root: Annotated[
        Connect
        | ConnectAck
        | Join
        | Welcome
        | DocChange
        | Ack
        | DocUpdate
        | ResyncRequest
        | Snapshot
        | PresenceUpdate
        | Ping
        | Pong
        | SessionClosed
        | Error
        | Checkpoint,
        Field(
            description='LiveClass IDE wire protocol — single source of truth. Pydantic and TS types are generated from this file; message shapes are never hand-written elsewhere.',
            title='Message',
        ),
    ]
