"""classes and session lifecycle

Revision ID: 756f3ca2c7a9
Revises: 451f8ee310c5
Create Date: 2026-10-02 08:44:01.091725

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '756f3ca2c7a9'
down_revision: str | None = '451f8ee310c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instructor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_instructor_id'), 'classes', ['instructor_id'], unique=False)
    op.add_column('sessions', sa.Column('class_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_sessions_class_id'), 'sessions', ['class_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'classes', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_class_id'), table_name='sessions')
    op.drop_column('sessions', 'class_id')
    op.drop_index(op.f('ix_classes_instructor_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
